pipeline {
    agent {
        label "dockerworker"
    }
    stages {
        stage('Build') {
            steps {
                dir('app') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        // stage('Test') {
        //     steps {
        //         dir('app') {
        //             sh 'mvn test'
        //         }
        //     }
        //     post {
        //         always {
        //             junit 'target/surefire-reports/*.xml'
        //         }
        //     }
        // }
        stage('Build image') {
            steps {
                dir('app') {
                    sh 'docker build -t bantosan .'
                }
            }
        }
        stage('Run app') {
            steps {
                dir('app') {
                    sh 'docker run bantosan'
                }
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}