pipeline {
    agent {
        label "dockerworker"
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Build image') {
            steps {
                sh 'docker build -t bantosan .'
            }
        }
        stage('Run app') {
            steps {
                sh 'docker run bantosan'
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}